name: CI

on:
  push:
    paths:
      - '*.swift'
      - 'Makefile'
      - '.github/workflows/*'
  pull_request:
    paths:
      - '*.swift'
      - 'Makefile'
      - '.github/workflows/*'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-12
    environment: ci
    steps:
      - uses: actions/checkout@v2

      - name: Download Xcode
        run: wget http://server.saagarjha.com/Xcode_14.0.1.xip.encrypted

        # I don't hate you, I just don't want to get sued
      - name: Decrypt Xcode
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: openssl enc -aes-256-cbc -d -pass 'env:ENCRYPTION_KEY' -in Xcode_14.0.1.xip.encrypted > Xcode_14.0.1.xip

      - name: Build unxip
        run: swift build --configuration release

      - name: Run unxip
        run: .build/release/unxip Xcode_14.0.1.xip

        # diff on Monterey is gnudiff, which exits with EXIT_TROUBLE (2) if
        # it finds problems. The Xcode bundle has a Ruby symlink that is
        # recursive, which trips this. So don't rely on the status, but
        # instead use the output exclusively.
      - name: Validate Xcode
        run: diff -r Xcode.app /Applications/Xcode_14.0.1.app > diff || true; cat diff && ! test -s diff
